"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000/api/v1";
type Job = { id: string; title: string; company: string; location?: string | null; description: string; source: string };
type Item = { id: string; title?: string; message?: string; state?: string; read_at?: string | null; details?: Record<string, unknown> };

async function api<T>(path: string, token: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${API}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init?.headers } });
  const data = await response.json().catch(() => null);
  if (!response.ok) throw new Error(data?.detail ?? "Request failed.");
  return data as T;
}

export default function HomePage() {
  const [token, setToken] = useState<string | null>(null); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [jobs, setJobs] = useState<Job[]>([]); const [notices, setNotices] = useState<Item[]>([]); const [activity, setActivity] = useState<Item[]>([]); const [selected, setSelected] = useState<Job | null>(null); const [query, setQuery] = useState("");
  useEffect(() => setToken(sessionStorage.getItem("jobpilot_token")), []);
  async function load(active = token) { if (!active) return; setError(""); try { const [j, n, a] = await Promise.all([api<{ jobs: Job[] }>(`/jobs?limit=25&offset=0${query ? `&q=${encodeURIComponent(query)}` : ""}`, active), api<Item[]>("/notifications?limit=10&offset=0", active), api<Item[]>("/activity?limit=10&offset=0", active)]); setJobs(j.jobs); setNotices(n); setActivity(a); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load workspace."); } }
  useEffect(() => { void load(); }, [token]); // eslint-disable-line react-hooks/exhaustive-deps
  async function login(e: FormEvent) { e.preventDefault(); try { const response = await fetch(`${API}/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data?.detail ?? "Sign in failed."); sessionStorage.setItem("jobpilot_token", data.access_token); setToken(data.access_token); } catch (cause) { setError(cause instanceof Error ? cause.message : "Sign in failed."); } }
  async function save() { if (!token || !selected) return; try { await api("/applications/records", token, { method: "POST", body: JSON.stringify({ job_id: selected.id, status: "SAVED" }) }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save opportunity."); } }
  if (!token) return <main className="auth"><section><p>JOBPILOT AI</p><h1>Consider every opportunity. Stay in control.</h1><span>Review jobs and track your search. Nothing is submitted automatically.</span></section><form onSubmit={login}><h2>Sign in</h2><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label>{error && <p className="error">{error}</p>}<button>Sign in</button><small>Registration remains available through the existing API.</small></form></main>;
  return <main className="shell"><aside><h2>✦ JobPilot AI</h2><p>Private workspace</p><Link className="profile-link" href="/profile">Profile & resumes</Link><Link className="profile-link" href="/jobs">Jobs</Link><span className="profile-link">Applications</span><button onClick={() => { sessionStorage.removeItem("jobpilot_token"); setToken(null); }}>Sign out</button></aside><section className="content"><header><div><p>PRIVATE WORKSPACE</p><h1>Your dashboard</h1></div><button onClick={() => void load()}>Refresh</button></header>{error && <p className="error">{error}</p>}<section className="hero"><div><p>YOUR JOB SEARCH, CLEARLY</p><h2>Move forward without handing over the decision.</h2><span>All private data is owner-scoped. Drafts and preference changes require explicit review.</span></div><b>✓ No automatic submissions</b></section><section className="grid"><article><h2>Opportunities</h2><form onSubmit={(e) => { e.preventDefault(); void load(); }}><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search jobs" /><button>Search</button></form>{jobs.map((job) => <button className="job" key={job.id} onClick={() => setSelected(job)}><small>{job.source}</small><b>{job.title}</b><span>{job.company} · {job.location ?? "Location not specified"}</span></button>)}{!jobs.length && <p>No opportunities found.</p>}</article><article>{selected ? <><small>{selected.source}</small><h2>{selected.title}</h2><p>{selected.company} · {selected.location ?? "Location not specified"}</p><p className="description">{selected.description}</p><button onClick={() => void save()}>Save to applications</button><small>Saving does not apply or submit anything.</small></> : <p>Select an opportunity to review details and take a safe next action.</p>}</article></section><section className="grid"><article><h2>Recent activity</h2>{activity.map((item) => <div className="row" key={item.id}><b>{item.state}</b><span>{item.message}</span></div>)}{!activity.length && <p>No activity yet.</p>}</article><article><h2>Notifications</h2>{notices.map((item) => <div className="row" key={item.id}><b>{item.read_at ? "READ" : "NEW"}</b><span>{item.title}: {item.message}</span></div>)}{!notices.length && <p>You’re up to date.</p>}</article></section></section></main>;
}
